In [1]:
import argparse, requests, re
import html
import pandas as pd
from os.path import join, isdir
import numpy as np

## Combine the fetched per-locus AFND data

AFND_data_locus_*.csv files were fetched with the `AFND_get_data_per_locus.ipynb` notebook. Here we clombine this clean data into a single list.

1. We load the per-locus data
2. We clean this data keeping only the populations that have information for each of the selected loci

**Output:** The final allele-frequency data is saved to the `AFND_data_locus_all.csv` file.

In [2]:
loci = ["A", "B", "C"]

full_df = None

for locus in loci:
    tmp_df = pd.read_csv("AFND_data_locus_{}.csv".format(locus))
    if full_df is None:
        full_df = tmp_df
    else:
        full_df = pd.concat([full_df, tmp_df])

In [3]:
full_df = full_df.reset_index()

full_df =full_df[full_df.columns[2:]]

In [4]:
full_df["Locus"] = full_df.Allele.apply(lambda x: x[0])

In [5]:
full_df

,Population,Allele,% of individuals that have the allele,Allele Frequency,Sample Size,Location,Allele - original,country,continent,Locus
0,American Samoa,A*02:01,NaN,0.130,51,14_18_S_170_42_W,A*02:01,American Samoa,Oceania,A
1,American Samoa,A*02:06,NaN,0.130,51,14_18_S_170_42_W,A*02:06,American Samoa,Oceania,A
2,American Samoa,A*03:01,NaN,0.020,51,14_18_S_170_42_W,A*03:01,American Samoa,Oceania,A
3,American Samoa,A*11:01,NaN,0.160,51,14_18_S_170_42_W,A*11:01,American Samoa,Oceania,A
4,American Samoa,A*11:04,NaN,0.010,51,14_18_S_170_42_W,A*11:04,American Samoa,Oceania,A
...,...,...,...,...,...,...,...,...,...,...
66752,Zimbabwe Harare Shona,C*14:03,NaN,0.004,230,17_51_S_31_1_E,C*14:03,Zimbabwe,Africa,C
66753,Zimbabwe Harare Shona,C*15:05,NaN,0.002,230,17_51_S_31_1_E,C*15:05,Zimbabwe,Africa,C
66754,Zimbabwe Harare Shona,C*16:01,NaN,0.080,230,17_51_S_31_1_E,C*16:01,Zimbabwe,Africa,C
66755,Zimbabwe Harare Shona,C*17:01,NaN,0.082,230,17_51_S_31_1_E,C*17:01,Zimbabwe,Africa,C
66756,Zimbabwe Harare Shona,C*18:01,NaN,0.049,230,17_51_S_31_1_E,C*18:01,Zimbabwe,Africa,C

### Keep only the populations that have data for all 3 loci

In [6]:
# keep only populations with all loci!!
uncovered_populations = []
for pop in full_df.Population.unique():
    print(pop)
    tmp = full_df[full_df.Population==pop].groupby(["Locus"])["Allele Frequency"].sum()
    print(tmp)
    covered_loci = list(tmp.reset_index().Locus)
    print(list(tmp.reset_index().Locus))
    if not ("A" in covered_loci \
       and "B" in covered_loci \
       and "C" in covered_loci):
        uncovered_populations.append(pop)

American Samoa
Locus
A    1.00
B    1.00
C    0.97
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Argentina Gran Chaco Eastern Toba
Locus
A    0.971
B    0.952
Name: Allele Frequency, dtype: float64
['A', 'B']
Argentina Gran Chaco Mataco Wichi
Locus
A    1.00
B    0.99
Name: Allele Frequency, dtype: float64
['A', 'B']
Argentina Gran Chaco Western Toba Pilaga
Locus
A    0.950
B    0.964
Name: Allele Frequency, dtype: float64
['A', 'B']
Argentina Rosario Toba
Locus
A    0.982
B    1.002
Name: Allele Frequency, dtype: float64
['A', 'B']
Armenia combined Regions
Locus
A    1.00
B    0.98
Name: Allele Frequency, dtype: float64
['A', 'B']
Australia Cape York Peninsula Aborigine
Locus
A    1.000
B    1.000
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Australia Groote Eylandt Aborigine
Locus
A    1.001
B    1.002
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Australia Kimberly Aborigine
Locus
A    1.000
B    0.999
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Australia New South Wales Caucasian
Locus
A    0.995
B    0.985
C    0.962
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Australia Yuendumu Aborigine
Locus
A    1.001
B    1.001
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Austria
Locus
A    1.097
B    1.000
Name: Allele Frequency, dtype: float64
['A', 'B']
Azores Central Islands
Locus
A    1.001
B    1.002
Name: Allele Frequency, dtype: float64
['A', 'B']
Azores Oriental Islands
Locus
A    0.999
B    1.004
Name: Allele Frequency, dtype: float64
['A', 'B']
Azores Terceira Island
Locus
A    0.960
B    1.016
Name: Allele Frequency, dtype: float64
['A', 'B']
Belgium
Locus
A    0.96
Name: Allele Frequency, dtype: float64
['A']
Bolivia/Chile Aymara NA-DHS_13 (G)
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Bolivia/Peru Quechua NA-DHS_12 (G)
Locus
A    1.0000
B    0.9998
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Barra Mansa Rio State Black
Locus
A    0.9990
B    0.9919
C    0.9642
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Barra Mansa Rio State Caucasian
Locus
A    0.9701
B    0.9908
C    0.9745
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Belo Horizonte Caucasian
Locus
A    0.957
B    1.002
Name: Allele Frequency, dtype: float64
['A', 'B']
Brazil Mixed
Locus
A    0.986
B    0.962
C    0.969
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Puyanawa
Locus
A    0.999
B    0.998
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Rio de Janeiro Black
Locus
A    0.9930
B    1.0003
C    0.9685
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Rio de Janeiro Caucasian
Locus
A    0.9866
B    0.9952
C    0.9829
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Rio de Janeiro Parda
Locus
A    0.9939
B    0.9846
C    0.9678
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Brazil Terena
Locus
A    1.000
B    0.994
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Bulgaria
Locus
A    1.000
B    0.995
Name: Allele Frequency, dtype: float64
['A', 'B']
Bulgaria Romani
Locus
A    0.999
B    0.996
C    0.953
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Cameroon Baka Pygmy
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Cameroon Beti
Locus
A    1.005
B    1.035
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Cameroon Sawa
Locus
A    0.997
B    0.958
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Cameroon Yaounde
Locus
A    0.998
B    0.993
Name: Allele Frequency, dtype: float64
['A', 'B']
Canada Chipewyan NA-DHS_2 (G)
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Canada Cree NA-DHS_3 (G)
Locus
A    1.0001
B    1.0003
C    1.0002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Canada Ojibwa NA-DHS_4 (G)
Locus
A    1.0000
B    0.9999
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Cape Verde Northwestern Islands
Locus
A    0.984
B    0.984
Name: Allele Frequency, dtype: float64
['A', 'B']
Cape Verde Southeastern Islands
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Chile Easter Island
Locus
A    1.001
B    0.905
C    0.928
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Chile Huilliche NA-DHS_14 (G)
Locus
A    1.0000
B    1.0000
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Chile Mapuche
Locus
A    1.0015
B    1.0023
Name: Allele Frequency, dtype: float64
['A', 'B']
China Beijing
Locus
A    1.063
B    0.982
C    1.005
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Beijing Shijiazhuang Tianjian Han
Locus
A    1.005
B    1.016
Name: Allele Frequency, dtype: float64
['A', 'B']
China Canton Han
Locus
A    1.000
B    0.998
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Guangdong Province Meizhou Han
Locus
A    0.994
B    0.990
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Guangxi Region Maonan
Locus
A    1.000
B    1.004
Name: Allele Frequency, dtype: float64
['A', 'B']
China Guangzhou
Locus
A    0.997
B    0.980
C    0.990
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Guizhou Province Bouyei
Locus
A    1.000
B    0.998
C    0.993
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Guizhou Province Miao pop 2
Locus
A    1.003
B    0.998
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Guizhou Province Shui
Locus
A    1.001
B    1.003
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Han HIV negative
Locus
A    1.001
B    1.000
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Henan HIV negative
Locus
A    1.001
B    1.000
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Hubei Han
Locus
A    0.9994
B    0.9997
C    0.9997
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Inner Mongolia Region
Locus
A    1.002
B    0.997
C    0.949
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Jiangsu Han
Locus
A    1.0005
B    1.0026
Name: Allele Frequency, dtype: float64
['A', 'B']
China Jiangsu Province Han
Locus
A    1.0000
B    1.0081
Name: Allele Frequency, dtype: float64
['A', 'B']
China Jingpo Minority
Locus
A    1.0007
B    0.9730
C    0.9970
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Marrow Donor Registry
Locus
A    1.000
B    1.001
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China North Han
Locus
A    1.001
B    1.003
C    1.003
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Qinghai Province Hui
Locus
A    0.9635
B    0.9990
C    1.0060
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Shanxi HIV negative
Locus
A    1.000
B    1.001
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Sichuan HIV negative
Locus
A    0.999
B    1.002
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China South Han
Locus
A    0.998
B    0.999
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Southwest Dai
Locus
A    0.999
B    0.998
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Tibet Region Tibetan
Locus
A    0.996
B    0.992
C    0.996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Uyghur HIV negative
Locus
A    0.998
B    0.998
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Yunnan Bulang
Locus
A    0.999
B    1.000
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Yunnan Hani
Locus
A    0.998
B    1.000
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Yunnan Province Han
Locus
A    1.001
B    1.005
C    1.003
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Yunnan Province Jinuo
Locus
A    0.999
B    1.003
Name: Allele Frequency, dtype: float64
['A', 'B']
China Yunnan Province Lisu
Locus
A    1.003
B    0.964
C    0.919
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
China Yunnan Province Nu
Locus
A    0.999
B    0.921
Name: Allele Frequency, dtype: float64
['A', 'B']
China Yunnan Province Wa
Locus
A    0.998
B    0.990
Name: Allele Frequency, dtype: float64
['A', 'B']
China Zhejiang Han
Locus
A    0.9990
B    0.9904
C    0.9951
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia Arhuaco NA-DHS_16 (G)
Locus
A    0.9999
B    1.0000
C    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia BogotÃ¡ Cord Blood
Locus
A    0.9994
B    1.0000
C    0.9997
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia Embera NA-DHS_19 (G)
Locus
A    0.9999
B    0.9999
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia Inga NA-DHS_11 (G)
Locus
A    0.9999
B    0.9998
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia Kogi NA-DHS_17 (G)
Locus
A    0.9999
B    0.9999
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia North Chimila Amerindians
Locus
A    0.9989
B    0.9987
C    0.9993
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia North Wiwa El Encanto
Locus
A    0.9997
B    0.9995
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia Waunana NA-DHS_20 (G)
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia Wayuu NA-DHS_15 (G)
Locus
A    0.9667
B    0.9999
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia Zenu NA-DHS_18 (G)
Locus
A    1.0000
B    1.0003
C    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia/Brazil Ticuna Arara NA-DHS_21 (G)
Locus
A    1.0000
B    0.9998
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Colombia/Brazil Ticuna Tarapaca NA-DHS_22 (G)
Locus
A    0.9999
B    0.9998
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Costa Rica African -Caribbean (G)
Locus
A    0.998
B    1.001
C    0.991
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Costa Rica Amerindians (G)
Locus
A    0.998
B    0.998
C    0.992
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Costa Rica Cabecar NA-DHS_9 (G)
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Costa Rica Central Valley Mestizo (G)
Locus
A    0.989
B    0.997
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Costa Rica Guanacaste Mestizo (G)
Locus
A    1.000
B    1.001
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Costa Rica Guaymi NA-DHS_10 (G)
Locus
A    1.0000
B    1.0002
C    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Croatia
Locus
A    0.994
B    0.989
Name: Allele Frequency, dtype: float64
['A', 'B']
Croatia pop 4
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Cuba Caucasian
Locus
A    0.978
B    0.995
Name: Allele Frequency, dtype: float64
['A', 'B']
Cuba Mixed Race
Locus
A    0.956
B    1.006
Name: Allele Frequency, dtype: float64
['A', 'B']
Czech Republic

Locus
A    0.903
Name: Allele Frequency, dtype: float64
['A']
Czech Republic NMDR
Locus
A    1.0002
B    1.0007
C    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Ecuador Amerindians
Locus
A    0.9994
Name: Allele Frequency, dtype: float64
['A']
England Blood Donors of Mixed Ethnicity
Locus
A    0.9927
B    0.9946
C    0.9951
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
England North West
Locus
A    1.001
B    1.000
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Finland
Locus
A    0.995
B    1.003
C    0.984
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
France French Bone Marrow Donor Registry
Locus
A    0.9822
B    0.9121
Name: Allele Frequency, dtype: float64
['A', 'B']
France Southeast
Locus
A    1.020
B    0.968
C    0.959
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Gaza
Locus
A    0.9997
B    0.9996
C    1.0001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Georgia Svaneti Region Svan
Locus
A    1.005
B    0.961
Name: Allele Frequency, dtype: float64
['A', 'B']
Georgia Tibilisi
Locus
A    0.998
B    1.000
C    0.991
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Georgia Tibilisi Kurd
Locus
A    1.003
B    0.994
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Austria minority
Locus
A    0.9995
B    1.0006
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Bosnia and Herzegovina minority
Locus
A    0.9999
B    1.0006
C    0.9992
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - China minority
Locus
A    0.9975
B    0.9998
C    0.9973
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Croatia minority
Locus
A    0.9991
B    0.9998
C    0.9991
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - France minority
Locus
A    0.9995
B    0.9993
C    0.9987
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - German donors
Locus
A    0.9944
B    0.9943
C    0.9942
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Greece minority
Locus
A    0.9995
B    0.9998
C    0.9988
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Italy minority
Locus
A    0.9956
B    0.9987
C    0.9951
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Netherlands minority
Locus
A    0.9989
B    1.0006
C    0.9987
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Portugal minority
Locus
A    0.9981
B    0.9990
C    0.9962
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Romania minority
Locus
A    0.9992
B    0.9994
C    0.9985
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Spain minority
Locus
A    0.9975
B    1.0002
C    0.9966
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - Turkey minority
Locus
A    1.0000
B    0.9993
C    0.9989
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany DKMS - United Kingdom minority
Locus
A    0.9974
B    0.9982
C    0.9958
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany pop 6
Locus
A    1.0001
B    1.0000
C    0.9991
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Germany pop 8
Locus
A    0.9945
B    0.9984
C    0.9992
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Ghana Ga-Adangbe
Locus
A    1.0000
B    1.0000
C    1.0001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Greece pop 6
Locus
A    1.0003
B    0.9981
C    0.9960
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Greece pop 8
Locus
A    1.0000
B    1.0001
C    0.9939
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Guatemala Kaqchikel NA-DHS_8 (G)
Locus
A    0.9998
B    0.9996
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Guinea Bissau
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Guinea Bissau Balanta
Locus
A    1.0
Name: Allele Frequency, dtype: float64
['A']
Guinea Bissau Bijago
Locus
A    1.0
Name: Allele Frequency, dtype: float64
['A']
Guinea Bissau Fula
Locus
A    1.0
Name: Allele Frequency, dtype: float64
['A']
Guinea Bissau Papel
Locus
A    1.0
Name: Allele Frequency, dtype: float64
['A']
Hong Kong Chinese
Locus
A    1.001
B    1.003
Name: Allele Frequency, dtype: float64
['A', 'B']
Hong Kong Chinese BMDR
Locus
A    1.0002
B    1.0006
C    1.0001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Hong Kong Chinese HKBMDR HLA 11 loci
Locus
A    0.9970
B    0.9880
C    0.9959
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Hong Kong Chinese cord blood registry
Locus
A    1.0000
B    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B']
India Andhra Pradesh Golla
Locus
A    0.979
B    1.002
Name: Allele Frequency, dtype: float64
['A', 'B']
India Andhra Pradesh Telugu Speaking
Locus
A    0.9709
B    0.9785
C    0.9923
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India Karnataka Kannada Speaking
Locus
A    0.987
B    0.971
C    0.958
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India Kerala Malayalam speaking
Locus
A    0.9825
B    0.9710
C    0.9420
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India Khandesh Region Pawra
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India Mumbai Maratha
Locus
A    0.982
B    1.001
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India New Delhi
Locus
A    1.001
B    1.005
C    0.985
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India North pop 2
Locus
A    0.935
B    0.991
Name: Allele Frequency, dtype: float64
['A', 'B']
India Tamil Nadu
Locus
A    0.9997
B    0.9999
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India Tamil Nadu Nadar
Locus
A    1.001
B    1.000
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
India West Coast Parsi
Locus
A    0.99
B    1.00
C    0.94
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Indonesia Java pop 2
Locus
A    1.001
B    0.977
Name: Allele Frequency, dtype: float64
['A', 'B']
Indonesia Sundanese and Javanese
Locus
A    1.002
B    0.955
Name: Allele Frequency, dtype: float64
['A', 'B']
Iran Baloch
Locus
A    0.976
B    0.961
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Iran Gorgan
Locus
A    1.0010
B    1.0040
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Iran Kurd pop 2
Locus
A    0.992
B    0.947
Name: Allele Frequency, dtype: float64
['A', 'B']
Iran Saqqez-Baneh Kurds
Locus
A    0.9999
B    0.9997
Name: Allele Frequency, dtype: float64
['A', 'B']
Iran Tabriz Azeris
Locus
A    1.0004
B    1.0007
Name: Allele Frequency, dtype: float64
['A', 'B']
Ireland Northern
Locus
A    1.002
B    1.014
C    1.005
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Ireland South
Locus
A    1.000
B    0.998
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Israel Arab Druze
Locus
A    1.000
B    1.000
C    0.995
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Israel Arab pop 2
Locus
A    0.9992
B    0.9995
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Argentina Jews
Locus
A    1.0001
B    0.9993
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Ashkenazi Jews pop 3
Locus
A    0.9997
B    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Ashkenazi and Non Ashkenazi Jews
Locus
A    0.987
B    0.994
C    0.926
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Israel Bukhara Jews
Locus
A    1.0004
B    0.9988
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Druze
Locus
A    0.9999
B    0.9995
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Ethiopia Jews
Locus
A    1.0005
B    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Georgia Jews
Locus
A    0.9992
B    0.9988
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Iran Jews
Locus
A    0.9996
B    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Iraq Jews
Locus
A    1.0002
B    0.9994
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Kavkazi Jews
Locus
A    0.9996
B    0.9993
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Libya Jews
Locus
A    0.9996
B    0.9983
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Morocco Jews
Locus
A    0.9994
B    0.9992
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Poland Jews
Locus
A    0.9995
B    0.9995
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel Tunisia Jews
Locus
A    1.0002
B    1.0002
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel USA Jews
Locus
A    1.0001
B    1.0001
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel USSR Jews
Locus
A    0.9995
B    0.9995
Name: Allele Frequency, dtype: float64
['A', 'B']
Israel YemenJews
Locus
A    0.9996
B    0.9991
Name: Allele Frequency, dtype: float64
['A', 'B']
Italy North pop 3
Locus
A    1.000
B    0.998
Name: Allele Frequency, dtype: float64
['A', 'B']
Italy pop 5
Locus
A    1.011
B    0.997
C    0.995
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Japan Central
Locus
A    0.998
B    0.994
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Japan Hokkaido Ainu
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Japan Okinawa Ryukyuan
Locus
A    0.987
Name: Allele Frequency, dtype: float64
['A']
Japan pop 16
Locus
A    1.0006
B    1.0020
C    1.0002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Japan pop 3
Locus
A    0.998
B    0.996
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Japan pop 5
Locus
A    0.999
B    0.999
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Kenya
Locus
A    0.987
B    0.983
C    0.986
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Kenya Luo
Locus
A    1.000
B    1.003
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Kenya Nandi
Locus
A    1.000
B    0.998
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Kenya, Nyanza Province, Luo tribe
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Kosovo
Locus
A    1.0000
B    1.0002
C    1.0001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Libya Cyrenaica
Locus
A    0.998
B    1.001
Name: Allele Frequency, dtype: float64
['A', 'B']
Madeira
Locus
A    0.978
B    0.997
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Champa
Locus
A    0.997
B    0.995
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Jelebu Temuan
Locus
A    1.001
B    1.002
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Kedah Baling Kensiu
Locus
A    0.9
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Kedah Kensiu
Locus
A    1.001
B    1.000
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Kelantan
Locus
A    1.002
B    1.003
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Mandailing
Locus
A    1.003
B    1.007
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Pahang Semai
Locus
A    0.998
B    1.000
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Patani

Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Malaysia Peninsular Chinese
Locus
A    1.0003
B    1.0010
C    1.0008
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Malaysia Peninsular Indian
Locus
A    0.9987
B    0.9992
C    0.9995
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Malaysia Peninsular Malay
Locus
A    1.0002
B    1.0001
C    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Malaysia Sarawak Bau Bidayuh
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Mali Bandiagara
Locus
A    0.995
B    0.994
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Chiapas Lacandon Mayans
Locus
A    1.0000
B    1.0004
C    1.0001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Chihuahua Chihuahua City Pop 2
Locus
A    0.9773
B    0.9888
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Chihuahua Tarahumara
Locus
A    0.998
B    1.000
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Guadalajara Mestizo pop 2
Locus
A    0.965
B    0.992
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Hidalgo Mezquital Valley/ Otomi
Locus
A    0.9930
B    0.9787
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Mestizo
Locus
A    0.997
B    0.995
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Mexico City Mestizo pop 2
Locus
A    0.9997
B    0.9976
C    0.9890
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Mexico City Mestizo population
Locus
A    0.9617
B    0.9900
C    0.9898
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Mexico City Tlalpan
Locus
A    0.9846
B    0.9904
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Mixe NA-DHS_6 (G)
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Mixtec
Locus
A    0.989
B    1.002
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Mixtec NA-DHS_5 (G)
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Oaxaca Jamiltepec Mixtec
Locus
A    0.997
B    0.998
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Oaxaca Mixe
Locus
A    0.999
B    1.000
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Oaxaca Mixtec
Locus
A    1.000
B    0.992
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Oaxaca Zapotec
Locus
A    0.998
B    0.965
C    0.991
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mexico Sonora Seri
Locus
A    0.969
B    0.999
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Veracruz Xalapa
Locus
A    0.9766
B    0.9948
Name: Allele Frequency, dtype: float64
['A', 'B']
Mexico Zapotec NA-DHS_7 (G)
Locus
A    1.0000
B    0.9996
C    1.0001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Mongolia Buryat
Locus
A    0.989
Name: Allele Frequency, dtype: float64
['A']
Morocco Atlantic Coast Chaouya
Locus
A    0.998
B    0.997
C    0.955
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Morocco Nador Metalsa pop 2
Locus
A    0.982
B    0.984
C    0.970
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Morocco Settat Chaouya
Locus
A    0.998
B    0.997
C    0.955
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Netherlands Leiden
Locus
A    1.000
B    0.990
C    0.993
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Netherlands UMCU
Locus
A    0.9998
B    0.9996
C    0.9686
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
New Caledonia
Locus
A    1.001
B    1.001
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
New Zealand Maori with Admixed History
Locus
A    1.003
B    1.007
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
New Zealand Maori with Full Ancestry
Locus
A    0.990
B    1.002
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
New Zealand Polynesians with Admixed History
Locus
A    1.000
B    1.005
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
New Zealand Polynesians with Full Ancestry
Locus
A    1.001
B    0.999
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Nicaragua Managua
Locus
A    1.0002
B    0.9994
C    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Nicaragua Mestizo (G)
Locus
A    0.992
B    0.977
C    0.997
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Oman
Locus
A    0.976
B    0.996
Name: Allele Frequency, dtype: float64
['A', 'B']
Pakistan Baloch
Locus
A    1.015
Name: Allele Frequency, dtype: float64
['A']
Pakistan Brahui
Locus
A    0.986
Name: Allele Frequency, dtype: float64
['A']
Pakistan Burusho
Locus
A    0.999
Name: Allele Frequency, dtype: float64
['A']
Pakistan Kalash
Locus
A    0.983
Name: Allele Frequency, dtype: float64
['A']
Pakistan Karachi Parsi
Locus
A    0.989
Name: Allele Frequency, dtype: float64
['A']
Pakistan Mixed Pathan
Locus
A    0.988
Name: Allele Frequency, dtype: float64
['A']
Pakistan Mixed Sindhi
Locus
A    0.994
Name: Allele Frequency, dtype: float64
['A']
Panama
Locus
A    0.9989
B    0.9907
C    0.9984
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Papua New Guinea East New Britain Rabaul
Locus
A    0.999
B    0.975
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Papua New Guinea Eastern Highlands Goroka Asaro
Locus
A    1.001
B    1.000
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Papua New Guinea Karimui Plateau Pawaia
Locus
A    1.001
B    1.001
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Papua New Guinea Madang
Locus
A    1.001
B    1.001
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Papua New Guinea West Schrader Ranges Haruai
Locus
A    1.001
B    1.001
C    0.919
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Papua New Guinea Wosera Abelam
Locus
A    1.001
B    1.065
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Paraguay/Argentina Ache NA-DHS_24 (G)
Locus
A    1.0000
B    1.0001
C    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Paraguay/Argentina Guarani NA-DHS_23 (G)
Locus
A    1.0000
B    0.9500
C    1.0002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Peru Titikaka Lake Uro
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Peru Titikaka Lake Uros
Locus
A    0.996
B    1.005
Name: Allele Frequency, dtype: float64
['A', 'B']
Philippines Ivatan
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Poland
Locus
A    0.947
B    0.991
C    0.960
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Poland BMR
Locus
A    0.9864
B    0.9961
C    0.9958
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Poland DKMS
Locus
A    0.9998
B    1.0001
C    1.0002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Portugal Azores Terceira Island
Locus
A    1.0004
B    1.0006
C    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Portugal Center
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Portugal North
Locus
A    0.999
B    0.970
Name: Allele Frequency, dtype: float64
['A', 'B']
Portugal South
Locus
A    0.999
B    0.996
Name: Allele Frequency, dtype: float64
['A', 'B']
Romania
Locus
A    0.974
B    0.965
Name: Allele Frequency, dtype: float64
['A', 'B']
Russia Bashkortostan, Tatars
Locus
A    0.9608
B    0.9502
Name: Allele Frequency, dtype: float64
['A', 'B']
Russia Belgorod region
Locus
A    0.9477
B    0.9905
C    0.9741
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Russia Bering Island Aleuts
Locus
A    0.9999
B    1.0000
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Russia Karelia
Locus
A    1.0007
B    1.0002
C    1.0004
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Russia Nizhny Novgorod, Russians
Locus
A    0.9372
B    0.9536
C    0.9175
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Russia Tundra Nentsi NA-DHS_1 (G)
Locus
A    1.0004
B    1.0004
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Russia Tuva pop 2
Locus
A    1.005
B    1.001
C    1.005
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Sao Tome Island Angolar
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Sao Tome Island Forro
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Saudi Arabia Guraiat and Hail
Locus
A    0.994
B    0.996
C    0.958
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Saudi Arabia pop 5
Locus
A    0.9410
B    0.9727
Name: Allele Frequency, dtype: float64
['A', 'B']
Saudi Arabia pop 6 (G)
Locus
A    0.9890
B    0.9933
C    0.9952
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Senegal Niokholo Mandenka
Locus
A    1.001
B    0.998
Name: Allele Frequency, dtype: float64
['A', 'B']
Singapore Chinese
Locus
A    0.994
B    0.997
Name: Allele Frequency, dtype: float64
['A', 'B']
Singapore Chinese Han
Locus
A    1.001
B    1.003
Name: Allele Frequency, dtype: float64
['A', 'B']
Singapore Javaneses
Locus
A    1.000
B    0.996
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Singapore Riau Malay
Locus
A    0.989
B    1.003
C    0.992
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Singapore SGVP Chinese CHS
Locus
A    0.997
B    0.999
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Singapore SGVP Malay MAS
Locus
A    1.001
B    1.005
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Singapore SGVP. Indian INS
Locus
A    0.998
B    1.003
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Singapore Thai
Locus
A    1.000
B    0.992
C    0.997
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
South Africa Caucasians
Locus
A    1.000
B    0.980
C    1.004
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
South Africa Natal Tamil
Locus
A    1.000
B    0.998
C    0.978
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
South Africa Natal Zulu
Locus
A    0.935
B    1.000
Name: Allele Frequency, dtype: float64
['A', 'B']
South Africa Worcester
Locus
A    0.996
B    0.994
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
South African Black
Locus
A    0.9895
B    0.9790
C    0.9720
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
South African Indian population
Locus
A    0.98
B    0.99
C    0.98
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
South African Mixed ancestry
Locus
A    1.00
B    0.98
C    1.00
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
South Korea pop 10
Locus
A    0.9999
B    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B']
South Korea pop 3
Locus
A    1.001
B    0.999
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Spain (Catalunya, Navarra, Extremadura, AaragÃ³n, Cantabria,
Locus
A    0.9996
B    0.9988
C    0.9994
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Spain, Canary Islands, Gran canaria island
Locus
A    0.9995
B    0.9999
C    1.0023
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Sri Lanka Colombo
Locus
A    1.001
B    1.001
C    1.003
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Sudan Mixed
Locus
A    1.009
B    1.069
Name: Allele Frequency, dtype: float64
['A', 'B']
Sweden Northern Sami

Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Sweden Southern Sami
Locus
A    1.0
B    1.0
Name: Allele Frequency, dtype: float64
['A', 'B']
Taiwan Ami
Locus
A    1.001
B    1.000
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Atayal
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Bunun
Locus
A    1.000
B    1.001
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Hakka
Locus
A    0.999
B    0.995
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Han Chinese
Locus
A    1.000
B    1.001
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Minnan pop 1
Locus
A    1.000
B    1.003
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Paiwan
Locus
A    1.000
B    1.000
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Pazeh
Locus
A    0.999
B    0.997
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Puyuma
Locus
A    1.00
B    1.00
C    0.95
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Rukai
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Saisiat
Locus
A    1.001
B    1.001
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Siraya
Locus
A    1.002
B    1.000
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Tao
Locus
A    1.0
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Taroko
Locus
A    1.000
B    1.000
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Thao
Locus
A    1.001
B    1.001
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Tsou
Locus
A    0.999
B    0.999
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan Tzu Chi Cord Blood Bank
Locus
A    0.999
B    1.003
Name: Allele Frequency, dtype: float64
['A', 'B']
Taiwan Tzu Chi Morrow Donor Registry
Locus
A    0.9998
B    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B']
Taiwan Tzu Chi Morrow Donor Registry Aborigine
Locus
A    0.9956
B    1.0000
Name: Allele Frequency, dtype: float64
['A', 'B']
Taiwan pop 2
Locus
A    0.991
B    0.977
C    0.986
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Taiwan pop 3
Locus
A    0.996
B    1.043
Name: Allele Frequency, dtype: float64
['A', 'B']
Tanzania Maasai
Locus
A    1.0000
B    1.0000
C    1.0009
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Tunisia
Locus
A    1.005
C    0.914
Name: Allele Frequency, dtype: float64
['A', 'C']
Tunisia Gabes
Locus
A    0.9987
B    1.0036
Name: Allele Frequency, dtype: float64
['A', 'B']
USA African American
Locus
A    1.005
B    1.004
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA African American Bethesda
Locus
A    1.001
B    0.926
C    0.980
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA African American pop 2
Locus
A    0.993
Name: Allele Frequency, dtype: float64
['A']
USA African American pop 3
Locus
A    0.992
B    0.998
C    0.977
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA African American pop 4
Locus
A    0.9996
B    0.9998
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Alaska Yupik
Locus
A    0.947
B    0.910
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Arizona Gila River Amerindian
Locus
A    0.999
B    0.998
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Arizona Gila River Pima
Locus
A    0.9984
B    0.9973
C    0.9989
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Arizona Pima
Locus
A    1.001
B    0.998
Name: Allele Frequency, dtype: float64
['A', 'B']
USA Asian
Locus
A    0.998
B    0.997
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Asian pop 2
Locus
A    1.0005
B    1.0005
C    1.0006
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Caucasian Bethesda
Locus
A    0.999
B    0.963
C    0.996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Caucasian pop 2
Locus
A    1.002
B    1.007
C    1.003
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Caucasian pop 3
Locus
A    1.001
Name: Allele Frequency, dtype: float64
['A']
USA Caucasian pop 4
Locus
A    0.9990
B    1.0000
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Eastern European
Locus
A    0.979
B    1.001
C    0.943
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Hawaii Okinawa
Locus
A    1.001
B    1.002
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Hispanic
Locus
A    0.999
B    0.995
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Hispanic pop 2
Locus
A    1.0009
B    1.0025
C    1.0010
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Italy Ancestry
Locus
A    0.999
B    1.001
C    1.003
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Mexican American Mestizo
Locus
A    0.994
B    1.000
C    0.996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP African
Locus
A    0.9987
B    0.9992
C    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP African American pop 2
Locus
A    0.9991
B    0.9984
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Alaska Native or Aleut
Locus
A    0.998
B    0.993
C    1.002
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP American Indian South or Central America
Locus
A    0.997
B    0.987
C    0.997
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Caribean Black
Locus
A    0.9960
B    0.9913
C    0.9976
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Caribean Hispanic
Locus
A    0.9995
B    0.9989
C    0.9997
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Caribean Indian
Locus
A    0.997
B    0.998
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Chinese
Locus
A    0.9994
B    0.9992
C    0.9994
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP European Caucasian
Locus
A    0.9989
B    0.9986
C    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Filipino
Locus
A    0.9998
B    0.9989
C    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Hawaiian or other Pacific Islander
Locus
A    0.9989
B    0.9982
C    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Hispanic South or Central American
Locus
A    0.9988
B    0.9993
C    0.9993
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Japanese
Locus
A    0.9717
B    0.9092
C    0.9981
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Korean
Locus
A    0.9991
B    0.9992
C    0.9995
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Mexican or Chicano
Locus
A    0.9987
B    0.9984
C    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Middle Eastern or North Coast of Africa
Locus
A    0.9989
B    0.9979
C    0.9993
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP North American Amerindian
Locus
A    0.9996
B    0.9991
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP South Asian Indian
Locus
A    0.9988
B    0.9997
C    0.9997
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Southeast Asian
Locus
A    0.9997
B    0.9993
C    1.0006
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA NMDP Vietnamese
Locus
A    0.9993
B    0.9991
C    0.9998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA New Mexico Canoncito Navajo
Locus
A    1.000
B    0.988
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA North American Native
Locus
A    1.001
B    0.996
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Philadelphia Caucasian
Locus
A    0.904
B    1.004
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA San Antonio Caucasian
Locus
A    0.9996
B    0.9965
C    0.9999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA San Diego
Locus
A    1.004
B    1.011
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA San Francisco Caucasian
Locus
A    1.000
B    0.998
C    0.998
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA South Dakota Lakota Sioux
Locus
A    0.997
B    1.001
C    0.936
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA South Texas Hispanic
Locus
A    0.989
B    0.981
C    0.989
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
USA Spain Ancestry
Locus
A    0.961
Name: Allele Frequency, dtype: float64
['A']
Uganda Kampala
Locus
A    0.999
B    0.983
C    0.996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Uganda Kampala pop 2
Locus
A    1.003
B    1.003
C    0.999
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
United Arab Emirates Abu Dhabi
Locus
A    0.9998
B    0.9995
C    0.9996
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Venezuela Perja Mountain Bari
Locus
A    1.000
B    0.999
Name: Allele Frequency, dtype: float64
['A', 'B']
Venezuela Sierra de Perija Yucpa
Locus
A    0.943
B    0.977
C    1.000
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Vietnam Hanoi Kinh pop 2
Locus
A    1.001
B    1.003
C    1.001
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Vietnam Kinh
Locus
A    0.9857
B    1.0010
C    0.9905
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Zambia Lusaka
Locus
A    1.003
B    0.990
C    0.977
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Zimbabwe Harare Shona
Locus
A    0.992
B    0.981
C    0.979
Name: Allele Frequency, dtype: float64
['A', 'B', 'C']
Cameroon Bamileke
Locus
B    0.973
C    0.997
Name: Allele Frequency, dtype: float64
['B', 'C']
China Beijing pop 2
Locus
B    1.0003
Name: Allele Frequency, dtype: float64
['B']
India Delhi pop 2
Locus
B    0.987
C    0.986
Name: Allele Frequency, dtype: float64
['B', 'C']
India West Bhil
Locus
B    1.0
C    1.0
Name: Allele Frequency, dtype: float64
['B', 'C']
Iran Yazd
Locus
B    0.9998
Name: Allele Frequency, dtype: float64
['B']
Ivory Coast Adiopodoume Akan
Locus
B    1.002
Name: Allele Frequency, dtype: float64
['B']
Malaysia Perak Grik Jehai
Locus
B    1.0
Name: Allele Frequency, dtype: float64
['B']
Papua New Guinea Wanigela Keapara
Locus
B    1.005
C    1.001
Name: Allele Frequency, dtype: float64
['B', 'C']
Russia Bashkortostan, Bashkirs
Locus
B    0.9671
Name: Allele Frequency, dtype: float64
['B']
Russian Federation Vologda Region
Locus
B    0.9787
C    0.9914
Name: Allele Frequency, dtype: float64
['B', 'C']
Serbia pop 2
Locus
B    1.0
Name: Allele Frequency, dtype: float64
['B']
Spain Andalusia Romani
Locus
B    0.997
C    0.954
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Aargau-Solothurn
Locus
B    0.9802
C    0.9931
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Basel
Locus
B    0.9753
C    0.9957
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Bern
Locus
B    0.9999
C    0.9940
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Geneva pop 2
Locus
B    0.9673
C    0.9875
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Graubunden
Locus
B    0.9923
C    0.9954
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Lausanne
Locus
B    0.9967
C    0.9933
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Lugano
Locus
B    0.9988
C    0.9933
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Luzern
Locus
B    0.9893
C    0.9916
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Sion
Locus
B    0.9985
C    0.9952
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland St Gallen
Locus
B    0.9854
C    0.9952
Name: Allele Frequency, dtype: float64
['B', 'C']
Switzerland Zurich

Locus
B    0.9844
C    0.9961
Name: Allele Frequency, dtype: float64
['B', 'C']
Thailand
Locus
B    0.960
C    1.001
Name: Allele Frequency, dtype: float64
['B', 'C']
Thailand pop 3
Locus
B    0.985
Name: Allele Frequency, dtype: float64
['B']
USA African American pop 8
Locus
B    1.008
Name: Allele Frequency, dtype: float64
['B']
USA European American pop 2
Locus
B    0.99
Name: Allele Frequency, dtype: float64
['B']
USA NMDP Black South or Central American
Locus
B    1.0273
Name: Allele Frequency, dtype: float64
['B']
China North Han pop 2
Locus
C    1.0003
Name: Allele Frequency, dtype: float64
['C']
China South Han pop 2
Locus
C    1.0007
Name: Allele Frequency, dtype: float64
['C']
Italy North
Locus
C    1.0
Name: Allele Frequency, dtype: float64
['C']
Italy South
Locus
C    1.002
Name: Allele Frequency, dtype: float64
['C']
Japan Kyoto and Osaka
Locus
C    0.984
Name: Allele Frequency, dtype: float64
['C']
Japan pop 1
Locus
C    0.999
Name: Allele Frequency, dtype: float64
['C']
Lebanon Mixed
Locus
C    0.987
Name: Allele Frequency, dtype: float64
['C']
Russia North Ossetian
Locus
C    0.9999
Name: Allele Frequency, dtype: float64
['C']
Russia Transbaikal Territory Buryats
Locus
C    1.001
Name: Allele Frequency, dtype: float64
['C']
Spain Andalusia
Locus
C    1.0
Name: Allele Frequency, dtype: float64
['C']
Spain Sevilla
Locus
C    1.0001
Name: Allele Frequency, dtype: float64
['C']
United Kingdom pop 3
Locus
C    0.993
Name: Allele Frequency, dtype: float64
['C']

In [7]:
clean_full_data = full_df[~full_df.Population.isin(uncovered_populations)].reset_index()

In [8]:
clean_full_data = clean_full_data[clean_full_data.columns[1:]]
clean_full_data

,Population,Allele,% of individuals that have the allele,Allele Frequency,Sample Size,Location,Allele - original,country,continent,Locus
0,American Samoa,A*02:01,NaN,0.130,51,14_18_S_170_42_W,A*02:01,American Samoa,Oceania,A
1,American Samoa,A*02:06,NaN,0.130,51,14_18_S_170_42_W,A*02:06,American Samoa,Oceania,A
2,American Samoa,A*03:01,NaN,0.020,51,14_18_S_170_42_W,A*03:01,American Samoa,Oceania,A
3,American Samoa,A*11:01,NaN,0.160,51,14_18_S_170_42_W,A*11:01,American Samoa,Oceania,A
4,American Samoa,A*11:04,NaN,0.010,51,14_18_S_170_42_W,A*11:04,American Samoa,Oceania,A
...,...,...,...,...,...,...,...,...,...,...
50555,Zimbabwe Harare Shona,C*14:03,NaN,0.004,230,17_51_S_31_1_E,C*14:03,Zimbabwe,Africa,C
50556,Zimbabwe Harare Shona,C*15:05,NaN,0.002,230,17_51_S_31_1_E,C*15:05,Zimbabwe,Africa,C
50557,Zimbabwe Harare Shona,C*16:01,NaN,0.080,230,17_51_S_31_1_E,C*16:01,Zimbabwe,Africa,C
50558,Zimbabwe Harare Shona,C*17:01,NaN,0.082,230,17_51_S_31_1_E,C*17:01,Zimbabwe,Africa,C
50559,Zimbabwe Harare Shona,C*18:01,NaN,0.049,230,17_51_S_31_1_E,C*18:01,Zimbabwe,Africa,C

In [9]:
clean_full_data.to_csv("AFND_data_locus_all.csv")